services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
        - action: rebuild
          path: package-lock.json
          target: /app/package-lock.json
    depends_on:
      db:
        condition: service_healthy
    environment:
      WEB_PORT: ${WEB_PORT}
    env_file:
      - path: .env
        required: true
    ports:
      - '${WEB_PORT}:3000'
    command: npx tsx ./src/index.ts

volumes:
  postgres_data:
